AWSTemplateFormatVersion: "2010-09-09"
Description:
  VPC and Subnet raisetechtask9

Resources:
#  VPC
  raisetechtask9VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: "true"
      EnableDnsSupport: "true"
      InstanceTenancy: default
      Tags:
      - Key: Name
        Value: raisetechtask9-vpc

# InternetGateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: raisetechtask9-IGW
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref raisetechtask9VPC
      InternetGatewayId: !Ref InternetGateway

# Subnet
  PublicSubnet1a:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: "ap-northeast-1a"
      CidrBlock: 10.0.10.0/24
      VpcId: !Ref raisetechtask9VPC
      Tags:
        - Key: Name
          Value: raisetechtask9-public-subnet-1a

  PublicSubnet1c:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: "ap-northeast-1c"
      CidrBlock: 10.0.11.0/24
      VpcId: !Ref raisetechtask9VPC
      Tags:
        - Key: Name
          Value: raisetechtask9-public-subnet-1c

  PrivateSubnet1a:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: "ap-northeast-1a"
      CidrBlock: 10.0.20.0/24
      VpcId: !Ref raisetechtask9VPC
      Tags:
        - Key: Name
          Value: raisetechtask9-private-subnet-1a

  PrivateSubnet1c:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: "ap-northeast-1c"
      CidrBlock: 10.0.21.0/24
      VpcId: !Ref raisetechtask9VPC
      Tags:
        - Key: Name
          Value: raisetechtask9-private-subnet-1c

# Route
  PublicRouteTable:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref raisetechtask9VPC
      Tags:
        - Key: Name
          Value: raisetechtask9-public-Route

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetRouteTableAssociationA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet1a

  PublicSubnetRouteTableAssociationC:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet1c

Outputs:
  VPC:
    Value: !Ref raisetechtask9VPC
    Export:
      Name: raisetechtask9-vpc

  PublicSubnet1a:
    Value: !Ref PublicSubnet1a
    Export:
      Name: raisetechtask9-public-subnet-1a

  PublicSubnet1c:
    Value: !Ref PublicSubnet1c
    Export:
      Name: raisetechtask9-public-subnet-1c

  PrivateSubnet1a:
    Value: !Ref PrivateSubnet1a
    Export:
      Name: raisetechtask9-private-subnet-1a

  PrivateSubnet1c:
    Value: !Ref PrivateSubnet1c
    Export:
      Name: raisetechtask9-private-subnet-1c
